name 'amaze_pdns'
maintainer 'Amaze Communication'
maintainer_email 'admin@amaze.com.au'
license 'Apache-2.0'
description 'Installs/Configures PowerDNS'
long_description 'Installs/Configures PowerDNS'
version '0.1.0'
supports 'debian', '>= 10'
chef_version '>= 14.0', '< 15'
depends 'postgresql', '~> 7.1.4'
#depends 'nginx', '~> 10.0.2'
source_url 'https://github.com/AmazeCom/amaze_pdns'
issues_url 'https://github.com/AmazeCom/amaze_pdns/issues'
